### ISSUE TITLE
Uncaught Error: dscId must be in the query parameters

### ISSUE THREAD

**Issue by spandl** [googledatastudio/ds-component#31]
I am getting a funny error message, that tells me to file bug...

```
index.js:72 Uncaught Error: dscId must be in the query parameters. This is a bug in ds-component, please file a bug: https://github.com/googledatastudio/ds-component/issues/new
    at Object../node_modules/@google/dscc/lib/index.js.exports.getComponentId (index.js:72)
    at Object../node_modules/@google/dscc/lib/index.js.exports.subscribeToData (index.js:352)
    at Module../Sunburst/sunburst.js (sunburst.js:17)
    at __webpack_require__ (bootstrap:19)
    at Object.1 (log.js:59)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
```

This happens while local testing and setting up a iFrame constellation like in final environnement.

The current workaround is to  call the iFrame with a query string 

```pug
iframe(src='vizframe.html?dscId=abc' componentid='abc' width='75%' height='750px')
```

**Comment by diminishedprime** [comment]
This is expected behavior. Are you setting up your own local testing environment, or using the one generated from `dscc-gen`?

**Comment by spandl** [comment]
Yes, I am currently trying my own test environment, because of this issue:
https://github.com/googledatastudio/dscc-gen/issues/38

However, I found a workaround as described. (I am now on the next hurdle - `MessageType: webpackOk is not supported by this version of the library.` - but will investigate some more before filing an issue...)
