### ISSUE TITLE
MessageType: webpackOk is not supported by this version of the library.

### ISSUE THREAD

**Issue by spandl** [googledatastudio/ds-component#32]
This might be related to issue #31 

Using my own work environment (using an iFrame setup), this message is always shown and breaks the script.

The visualization is however working in the live Data Studio environment, this happens only in the local environment.

I am not using the dssc-gen component because of:
https://github.com/googledatastudio/dscc-gen/issues/38

**Question**
Is there an alternative way of making a local environment work?

**Error message**
```
MessageType: webpackOk is not supported by this version of the library.
onMessage_1 @ VM444 sunburst.js:878
postMessage (async)
sendMsg @ VM444 sunburst.js:27183
ok @ VM444 sunburst.js:26653
(anonymous) @ VM444 sunburst.js:26911
sock.onmessage @ VM444 sunburst.js:26523
EventTarget.dispatchEvent @ VM444 sunburst.js:19532
(anonymous) @ VM444 sunburst.js:20249
SockJS._transportMessage @ VM444 sunburst.js:20247
EventEmitter.emit @ VM444 sunburst.js:19448
WebSocketTransport.ws.onmessage @ VM444 sunburst.js:22323

```

```JS
var onMessage_1 = function (message) {
            if (message.data.type === types_1.MessageType.RENDER) {
                cb(options.transform(message.data));
            }
            else {
                console.error("MessageType: " + message.data.type + " is not supported by this version of the library.");
            }
        };
```

**Comment by habibdhif** [comment]
I had this problem too, what i did to fix it is simply set `const LOCAL = true;` in `index.js` when working in a local environment and reset it to `false` before pushing to the *Storage Bucket*.
PS: The `LOCAL` constant is used in this code block in `index.js`
```
if (LOCAL) {
  draw(local.message);
} else {
  dscc.subscribeToData(draw, {transform: dscc.objectTransform});
}
```

**Comment by spandl** [comment]
Thank-You. I can confirm that this solution worked for me as well.
